### ISSUE TITLE
No option to Export as PDF

### ISSUE THREAD

**Issue by dmonder** [OliverBalfour/obsidian-pandoc#104]
I have many different options under Export as (ePub, LaTeX, DokuWiki, MediaWiki, Beamer Slides, AsciiDoc, Pandoc Markdown, Reveal.js Slides, PowerPoint, OpenDocument, Word Document, HTML, and reStructured Text. However, I see no Export to PDF option.

**Comment by shanest** [comment]
Just wanted to echo that I am also having this issue

**Comment by MacGros** [comment]
Hey,
Same here !

**Comment by Liong1976** [comment]
The same here

**Comment by apotenza92** [comment]
Seems the option to export as PDF isn't visible unless the plugin is configured correctly. I had to manually put in my Pandoc and PDFLatex path in the settings to get the PDF option to appear. I used `winget` on windows and `brew` on macOS. Full instructions are here: https://pandoc.org/installing.html I just used `winget` instead of `choco` because winget is native to Windows now.

After doing the below and restarting Obsidian the option to export as PDF appeared.

## Windows

Install Pandoc

```
winget install pandoc
```

Install Miktex

```
winget install miktex
```

Pandoc Path

```
C:\Users\[username]\AppData\Local\Pandoc\pandoc.exe
```

PDFLatex Path

```
C:\Program Files\MiKTeX\miktex\bin\x64\miktex.exe
```

## Mac

Install Pandoc

```
brew install pandoc
```

Install BasicTex

```
brew install homebrew/cask/basictex
```

Pandoc Path

```
/opt/homebrew/bin/pandoc
```

PDFLatex Path

```
/Library/TeX/texbin/pdflatex
```

**Comment by dmonder** [comment]
That fixed it. Thank you.
