### ISSUE TITLE
Inject CSS in HTML export

### ISSUE THREAD

**Issue by EhuddR** [OliverBalfour/obsidian-pandoc#14]
Hello! First of all this plugin is excellent. I would like to know if there is a possibility to export your notes to html but keeping the CSS style of your Obsidian theme. It would be really helpful because I want to use github and netlify to manage a personal blog so I could export my notes directly with the css settings already included.

Best regards.

**Comment by OliverBalfour** [comment]
I'm glad to hear it!

Yes, that feature is on my radar - I will probably have this done by the end of next week. Currently it just injects some light theme CSS, but it shouldn't be too hard to use the active 3rd party theme instead if any.

If you want to do this right now, there is currently a custom CSS loading feature where you specify a file to load from. You could try setting "Custom CSS file for HTML output" to `.obsidian/themes/YourTheme.css`, but I've heard mixed reports of whether it works or not.

**Comment by OliverBalfour** [comment]
Fixed in 2fea023

There's now an "Inject app CSS" setting where you can choose to inject the CSS from light/dark/active/no theme.

There's also a separate "Inject entire 3rd party theme CSS file" setting which usually isn't needed and bulks up the file size a lot (themes have lots of redundant CSS code).

Plus, there's the "Custom CSS file for HTML output" setting still as a fallback if neither of the above suit your needs.

**Comment by EhuddR** [comment]
Thank you. The plugin is awesome. Really good job. 

Regards.
