### ISSUE TITLE
Multimedia embeds (PDF, audio, etc.)

### ISSUE THREAD

**Issue by OliverBalfour** [OliverBalfour/obsidian-pandoc#18]
For the HTML output, it might be nice to have PDF embeds work (note: be careful with the `![[doc.pdf#page=number]]` syntax). Audio/video is relatively easy, not sure about PDF though.

For export types other than HTML, multimedia embeds should just be stripped entirely. There's no value in leaving behind filenames or other artefacts, it should just be purged.

**Comment by OliverBalfour** [comment]
Actually, I can't think of any real application for this - if you want video embeds you can use HTML anyway. Closing as I can't justify spending time on this

**Comment by Gewerd-Strauss** [comment]
However, if one tries to embed an audiofile, the plugin will silently crash, while printing to console only: 

![grafik](https://user-images.githubusercontent.com/80548781/175126755-a7a805a5-5e1f-4a27-9f80-c28014c9d47d.png).
Note that the plugin cannot find a _picture_. Howver, changing the audio file embed to a simple link - or removing it completely - results in the plugin successfully generating a docx-file.

Embedded was  `!{{MeetingLV_22.06.2022.mp3}}`, located at vault root. All other images, including the alleged missing `Pasted image 20220622125744.png` are located ad root as well.

This error is not visible outside of the console. Obsidian will then freeze, forcing the user to close it externally and then restart it. No (in my case docx-)file is generated.

This might also be triggered by embedding another filetype, but so far I could only test and replicate this bug for mp3-audiofiles, and webm-video files (aka the video files creation by the audio recorder plugin - why the heck does this thing write a video-format instead of an audio-format to begin with?)
