### ISSUE TITLE
Feature request: Support inclusion of mermaid diagrams in export

### ISSUE THREAD

**Issue by anthrolisp** [OliverBalfour/obsidian-pandoc#2]
Feature request: Support inclusion of mermaid diagrams in export

**Comment by OliverBalfour** [comment]
I think this works for HTML but the styling is wrong for other export options. Does that match what you've seen?

Either way, I'll try and patch this by the end of next week, mermaid diagrams are pretty useful.

Thanks for reporting this!

**Comment by OliverBalfour** [comment]
It looks like the cause here is that I'm injecting CSS to make Mermaid diagrams look right, but Pandoc strips all CSS when converting. HTML output looks fine as I don't use Pandoc for that, but everything else looks wrong.

The Mermaid SVG output must have its own styling embedded which looks weird, this is what needs to be fixed. Unsure how I will fix this just yet - I'll have to somehow replace the SVG element `style` attributes with my own styles.

Note to self: Mermaid images don't appear in the Reveal.js output they are malformed images. To fix this you need to extract the base-64 encoded string from `<img src="data:image/svg+xml;base64,MERMAID_BASE64"/>` and set `image.outerHTML = atob(base64)`.

**Comment by OliverBalfour** [comment]
It also looks like exporting to a PDF with Mermaid diagrams causes an error because LaTeX (or at least my installation) doesn't support SVG diagrams, which Mermaid diagrams are. I'll look in to replacing Mermaid SVG images with PNGs in places where they cause problems eventually, but as there's already a working PDF export feature I won't worry about the PDF issue for now.

**Comment by OliverBalfour** [comment]
Fixed! Here's an example mermaid diagram in a Word document export:

![image](https://user-images.githubusercontent.com/11626018/114684376-3364f480-9d54-11eb-8432-90ec6bfc7e1e.png)

It just converts the SVG to a PNG and uses that instead.

**Comment by OliverBalfour** [comment]
Oops, I just realised the arrowheads are missing. Looks like a trivial fix, I'll have it done tonight.

Also, currently the Mermaid diagram styles are restricted to the light theme, but I'll consider adding a setting to change that as it seems a little restrictive.

**Comment by OliverBalfour** [comment]
Here we go, works like a charm:

![image](https://user-images.githubusercontent.com/11626018/114698034-f7d12700-9d61-11eb-87df-a7947844595b.png)
