### ISSUE TITLE
request: option to set attachments folder

### ISSUE THREAD

**Issue by firinael** [OliverBalfour/obsidian-pandoc#20]
Currently, if you have embedded images in your note, they must be in the same directory as the note to be exported.

I ask that an option to set the designated attachments folder is added, so as to not have to move the images to the note directory every time you want to export something.

**Comment by OliverBalfour** [comment]
Thanks for testing this! That's definitely a bug, I was hoping relative paths would resolve correctly. Hopefully this will be fixed by the end of next week.

I think the best approach is to use the same logic for finding images that the Obsidian HTML preview does. If Obsidian has an attachments folder setting, then I'll use that setting too. My vault is a giant flat folder, so I'll have to do some testing with subfolders to see exactly how it works.

Note to self: be careful about images inside embedded notes - paths should resolve relative to the files they're embedded in, and embedded notes should have paths re-resolved to be relative to the file they're embedded in.

**Comment by OliverBalfour** [comment]
FYI, the latest version half works - it uses relative paths, whereas Obsidian seems to pretend everything is in the same folder.

If you have an image in a folder called `images` which you embed using `![[images/image.png]]` in a note in the root of your vault, then exporting the note will work correctly.

I'll still fix this issue soon, just thought I'd mention a temporary workaround.

**Comment by OliverBalfour** [comment]
Closing in favour of #29 which is the same underlying issue

**Comment by FrankZter** [comment]
I still have the problem, that pandoc does not find the images when they are in my attachment folder...

**Comment by radoslawg** [comment]
Same issue here. Images in separate attachement folder are not found when exported. #29 is also closed but it did not help. Should we wait for #23 now?

**Comment by Gewerd-Strauss** [comment]
Same issue here. Especially  if you have specific assets-folders per subfolder. Still need to move all images to the root of the vault for the plugin to work.

**Comment by memelet** [comment]
I too need to move the attachments up to the root.

**Comment by mich2k** [comment]
Having yet the same issue

**Comment by sOER-Frank** [comment]
Still having the issue
