### ISSUE TITLE
French (and other language) accent

### ISSUE THREAD

**Issue by Mara-Li** [OliverBalfour/obsidian-pandoc#22]
The accent (like `é`, `é`, `à`...) doesn't seem to work :
![image](https://user-images.githubusercontent.com/30244939/115207619-0e79d400-a0fc-11eb-8763-95f6b86b68c0.png)

**Comment by OliverBalfour** [comment]
Thanks for reporting this!

The issue is I wrote my plugin to strip all non-ASCII characters before using Pandoc to create LaTeX (and thus PDF) output because the default LaTeX engine doesn't support most Unicode characters. I forgot that most languages use non-ASCII characters... oops!

This should be a trivial fix, I'll likely have it done by the weekend. Sorry about this!
