### ISSUE TITLE
Feature request: Ability to define TITLE

### ISSUE THREAD

**Issue by anthrolisp** [OliverBalfour/obsidian-pandoc#3]
Feature request: Ability to define the title either with YAML, or by having name of note be the title by default.

**Comment by OliverBalfour** [comment]
Thanks for adding this. I assume you mean the Pandoc metadata title, not the filename, right?

Currently the metadata title is set to be the name of the note/filename. This is why the PDF export's first page has the note name displayed and why the HTML export will show the note name as the name of the tab in your browser.

Are you suggesting that if you write this at the top of your file:

`Some Note with ugly filename.md`:
```md
---
title: The title you want instead of the filename
... More YAML front matter
---
Contents of note
```

Then it uses the YAML title field instead of the filename, and it uses the filename if there isn't a YAML title?

If so, that's a great idea! I'll probably add it by the end of the week

**Comment by SkepticMystic** [comment]
iirc, pandoc does this already. If `title` yaml field is present, that is used. Otherwise the file name is the default. So yeah, this behaviour would align nicely 🙂
