### ISSUE TITLE
Preserve CSS settings

### ISSUE THREAD

**Issue by DutchPete** [OliverBalfour/obsidian-pandoc#42]
We once had a discussion about the possibility of preserving/adding CSS settings for export to PDF.
Since it is not listed in your features, I wonder if this is still pending? Is it even on your roadmap?

**Comment by OliverBalfour** [comment]
Hi,
Unfortunately CSS is not really recognised by Pandoc when creating LaTeX/PDF outputs. By default the CSS is getting included, but it has no effect.

If you want a PDF with custom styling there are two approaches:
1. the inbuilt Obsidian "Export to PDF" feature is pretty good
2. you could export to HTML with my plugin, open the HTML in your browser, and print that to a PDF file

**Comment by DutchPete** [comment]
OK. I installed the plug-in manually, i.e. downloaded from Github then added to the Obsidian vault.
In the plug-in settings it shows this:
![image](https://user-images.githubusercontent.com/10794265/123503132-97ac0a80-d659-11eb-821e-b3f13f57077d.png)

I don't understand that because Pandoc *is* installed:
![image](https://user-images.githubusercontent.com/10794265/123503178-f7a2b100-d659-11eb-8656-ca08077538ba.png)

**Comment by OliverBalfour** [comment]
Hi Peter,
That looks like a PATH variable issue, which happens a lot on Mac and Linux with this plugin because of how Obsidian is launched outside of a terminal.
To fix this, try running `which pandoc` in your terminal to find the exact location of the pandoc executable, and then put it in the `Pandoc path` setting:

![image](https://user-images.githubusercontent.com/11626018/123504850-0a8ba480-d69f-11eb-88a8-5d227e8cb8c4.png)

I think after setting this, you have to reload Obsidian for the changes to take effect.
I realise this is not an obvious fix, so I'll update the documentation to mention it

Let me know if you have any further issues

**Comment by DutchPete** [comment]
I am on a Mac, and based on your reply this is what I added:
![image](https://user-images.githubusercontent.com/10794265/123505000-4dc92180-d665-11eb-902a-84f22b400aa9.png)

But then the browser cannot open the file: the browser tab remains blank and the wheel keeps spinning.

**Comment by OliverBalfour** [comment]
That's the correct path, but it looks like you've just added it to the wrong field - it should be "Pandoc path", not the CSS field. The reason it's taking a while to load is because my plugin is thinks the 70MB pandoc binary is a CSS file, and your browser is not happy... 😂

To fix this, you'll just need to empty the CSS file field, put the path in the `Pandoc path` field instead, and delete the horrifying HTML export containing a 70MB binary my plugin thought you wanted lol

**Comment by DutchPete** [comment]
I apologize: you did mention the `Pandoc path` in the 1st reply but I had not seen you need to scroll down the settings page to get to it. So, it works now.

What do you mean by that 70MB binary? Where is it stored?

**Comment by OliverBalfour** [comment]
No need to apologise! The settings page is pretty length and confusing, I understand. Besides, hearing my plugin made an HTML file containing 70MB of gibberish just made my day 😛

As for the binary, I just meant that the file `/usr/local/bin/pandoc` is a 70MB executable/application file, often called a binary file too. When you write `pandoc ...` in the terminal, it's just running that file as an application with the `...` arguments you give it.

**Comment by DutchPete** [comment]
So, do I need to delete anything or were you just joking?

**Comment by OliverBalfour** [comment]
It sounds like you exported an HTML file which your browser couldn't load, if that's the case you should probably delete the failed export. (No big deal if you can't find it though - it won't break anything.) But don't delete the `/usr/local/bin/pandoc` file of course. Sorry about the confusion!

**Comment by DutchPete** [comment]
Ah, OK. Yes, I deleted that file as soon as I saw the browser could not open it.
Thanks for your help and patience.
