### ISSUE TITLE
Feature request: Export whole folder to different formats with internal links preserved

### ISSUE THREAD

**Issue by bhickta** [OliverBalfour/obsidian-pandoc#47]
## Current issue
* When currently exporting any file into other format [.docx, .html], internal links doesn't works
## Request
* Docx: When exporting a index page, that page would become "Table of content" of the embeeded content in same document
* Html: Export index page with all [[internally linked pages]], so that [[internal link]] would be preserved

**Comment by OliverBalfour** [comment]
1. Internal links are disabled by default in exports, but there's an `Internal link processing` setting that should come in handy
2. It's a little tricky to tell if a page is an index page, but there's a simple way to get this behaviour: just use `![[note embeds]]` instead of `[[wikilinks]]`, and make a copy of the index at the top as a table of contents. Generating tables of contents isn't really in the scope of this plugin but it shouldn't be too hard to do yourself. Sorry about this!
3. Good idea! If I implement batch exports (#10), I will definitely consider adding this feature
